# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'market.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QLabel, QLineEdit,
    QListView, QMainWindow, QPushButton, QSizePolicy,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(557, 351)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setContextMenuPolicy(Qt.NoContextMenu)
        MainWindow.setWindowTitle(u"MainWindow")
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"")
        self.listView = QListView(self.centralwidget)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(15, 20, 150, 255))
        self.listView.setStyleSheet(u"")
        self.listView.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.listView.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.listView.setAutoScrollMargin(14)
        self.listView.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.listView.setProperty("showDropIndicator", False)
        self.listView.setMovement(QListView.Static)
        self.listView.setResizeMode(QListView.Fixed)
        self.listView.setLayoutMode(QListView.Batched)
        self.item_search = QLineEdit(self.centralwidget)
        self.item_search.setObjectName(u"item_search")
        self.item_search.setGeometry(QRect(51, 320, 115, 19))
        self.item_search.setFocusPolicy(Qt.ClickFocus)
        self.item_search.setContextMenuPolicy(Qt.NoContextMenu)
        self.item_search.setAcceptDrops(False)
        self.item_search.setStyleSheet(u"")
        self.search = QLabel(self.centralwidget)
        self.search.setObjectName(u"search")
        self.search.setGeometry(QRect(52, 304, 49, 16))
        self.start_button = QPushButton(self.centralwidget)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setEnabled(False)
        self.start_button.setGeometry(QRect(455, 320, 82, 20))
        self.start_button.setStyleSheet(u"")
        self.start_button.setCheckable(True)
        self.tutorial_button = QPushButton(self.centralwidget)
        self.tutorial_button.setObjectName(u"tutorial_button")
        self.tutorial_button.setGeometry(QRect(420, 5, 82, 16))
        self.tutorial_button.setStyleSheet(u"")
        self.load_button = QPushButton(self.centralwidget)
        self.load_button.setObjectName(u"load_button")
        self.load_button.setEnabled(True)
        self.load_button.setGeometry(QRect(90, 277, 37, 16))
        self.load_button.setStyleSheet(u"")
        self.load_button.setCheckable(False)
        self.save_button = QPushButton(self.centralwidget)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setEnabled(True)
        self.save_button.setGeometry(QRect(129, 277, 37, 16))
        self.save_button.setStyleSheet(u"")
        self.settings_button = QPushButton(self.centralwidget)
        self.settings_button.setObjectName(u"settings_button")
        self.settings_button.setEnabled(True)
        self.settings_button.setGeometry(QRect(504, 5, 16, 16))
        self.settings_button.setStyleSheet(u"")
        self.minimize_button = QPushButton(self.centralwidget)
        self.minimize_button.setObjectName(u"minimize_button")
        self.minimize_button.setEnabled(True)
        self.minimize_button.setGeometry(QRect(522, 5, 16, 16))
        self.minimize_button.setAutoFillBackground(False)
        self.minimize_button.setStyleSheet(u"")
        self.x_button = QPushButton(self.centralwidget)
        self.x_button.setObjectName(u"x_button")
        self.x_button.setEnabled(True)
        self.x_button.setGeometry(QRect(540, 5, 16, 16))
        self.x_button.setStyleSheet(u"")
        self.search_button = QPushButton(self.centralwidget)
        self.search_button.setObjectName(u"search_button")
        self.search_button.setEnabled(True)
        self.search_button.setGeometry(QRect(148, 322, 16, 16))
        self.search_button.setStyleSheet(u"")
        self.search_button.setCheckable(False)
        self.Image = QWidget(self.centralwidget)
        self.Image.setObjectName(u"Image")
        self.Image.setGeometry(QRect(14, 308, 35, 35))
        self.image = QLabel(self.Image)
        self.image.setObjectName(u"image")
        self.image.setGeometry(QRect(0, 0, 35, 35))
        self.image.setAutoFillBackground(False)
        self.image.setAlignment(Qt.AlignCenter)
        self.select_client = QPushButton(self.centralwidget)
        self.select_client.setObjectName(u"select_client")
        self.select_client.setGeometry(QRect(330, 5, 82, 16))
        self.select_client.setStyleSheet(u"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.listView.raise_()
        self.item_search.raise_()
        self.search.raise_()
        self.tutorial_button.raise_()
        self.load_button.raise_()
        self.save_button.raise_()
        self.settings_button.raise_()
        self.minimize_button.raise_()
        self.x_button.raise_()
        self.search_button.raise_()
        self.start_button.raise_()
        self.Image.raise_()
        self.select_client.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

